### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by huang123ying** [xiangdal/implicit_alignment#1]
when i run the MDD+implicit,should i set the args.self_training==True?

**Comment by xiangjjj** [comment]
Yes, please set `args.self_train=True`. This argument is designed exclusively for the target domain so that it can collect pseudo-labels and use them for sampling. More detail please refer to [here](https://github.com/xiangdal/implicit_alignment/blob/master/ai/domain_adaptation/datasets/data_provider.py#L107). BTW, I noticed that I forgot to include it in the readme, but it is in my `makefile` scripts, such as [this](https://github.com/xiangdal/implicit_alignment/blob/master/ai/domain_adaptation/makefiles/Makefile_officehome_imbalanced). Please let me know if this answers you question. Thanks!

**Comment by xiangjjj** [comment]
I've just updated the readme to correct this. Please refer to the [makefile scripts](https://github.com/xiangdal/implicit_alignment/tree/master/ai/domain_adaptation/makefiles) for the configuration of different datasets.

**Comment by huang123ying** [comment]
thank you very much!
